POST http://localhost:3003/api/procedures
Content-Type: application/json
Authorization: bearer

{
  "jib": "440266337007874",
  "category": "konkurentski zahtjev",
  "number": "987-7-1-88/22",
  "name": "Nabavka tonera",
  "frameworkAgreement": false,
  "criterion": "najniža cijena",
  "auction": true,
  "submissionDate": "2022-07-18 14:00:00",
  "budget": 20000.00,
  "deliveryLocation": "Banja Luka",
  "deliveryDate": 30,
  "payment": 30,
  "offerValidity": 90,
  "filledDraft": false,
  "copy": 0,
  "amount": 19000.00,
  "phase": "Čeka se odluka"
}
